### PR TITLE
Use NameAcquired/NameLost signals for name tracking.

### LINKED ISSUE #23: DBus activation doesn't work for initial method call
DBus activation has the following event flow:

1. Process A makes a DBus method call with DBus name "com.example.Foo" and method "com.example.Interface.MethodName."
2. DBus notices that there is no process on the bus with the name "com.example.Foo."
3. DBus launcher looks through /usr/share/dbus-1/services (for session bus services) for a .service file for a DBus service with the name "com.example.Foo." If it doesn't find one, it returns a "No such service" error and breaks this flow.
4. If it does find one, it launches the process with the information from the .service file.
5. It waits until the process has been granted the name "com.example.Foo" (i.e the NameAcquired signal).
6. It sends the method call to the process.

The problem for godbus is the time between steps 5 and 6. Since the name request (and corresponding NameAcquired signal) are handled asynchronously, and the method call is also handled asynchronously, and the time between steps 5 and 6 is minuscule, it's possible (indeed, it happens every time for me) for the NameAcquired signal to be emitted but not completely handled before the method call comes in as well. This results in the method call being discarded since godbus hasn't saved the fact that the name has been acquired, so godbus thinks the message came in via an eavesdrop with no corresponding channel.

This results in the initial method call (which caused the activation) to receive no reply. Subsequent method calls work fine since the NameAcquired signal has since been handled.

There needs to be some way of synchronously acquiring the name (or at least synchronously handling that signal before handling another message), or godbus simply can't be used for DBus activation.

### PR DESCRIPTION
**Pull request by kyrofa**
This MR fixes #23 by changing the name tracking to be 100% signal-based. Previously, the result of RequestName()/ReleaseName() was used for name tracking, but such an implementation precluded the use of DBus activation due to the order of events in DBus.

### CODE REVIEW

**Comment by kyle-f** [comment]
@philips this is a critical issue for our usage and a very small patch-- please review as soon as you can.

**Comment by philips** [comment]
lgtm, @bcwaldon @alexlarsson ?

**Comment by kyrofa** [comment]
@bcwaldon I've having to maintain a local fork so this feature works... please look at this as soon as you can.

**Comment by philips** [comment]
ping @bcwaldon @alexlarsson ?

File: conn.go [hunk 1]
```diff
@@ -303,18 +303,27 @@ func (conn *Conn) inWorker() {
...
+							if v == name {
+								conn.names = append(conn.names[:i],
+									conn.names[i+1:]...)
+							}
 						}
+						conn.namesLck.Unlock()
+					} else if member == "NameAcquired" {
+						// If we acquired the name on the bus, add it to our
+						// tracking list.
+						name, _ := msg.Body[0].(string)
```
Comment (bcwaldon) [inline conn.go]: It would be better to check the second value and panic rather than silently hide errors to aid in future debugging

**Comment by bcwaldon** [comment]
LGTM after one minor nit is addressed

File: conn.go (hunk 1 above)
Comment (kyrofa) [inline conn.go]: I don't have a problem with that, but it changes the behavior from what was previously written (the old line 309). I'll push that up.

**Comment by kyrofa** [comment]
@bcwaldon pushed again to address your concerns.

File: conn.go (hunk 1 above)
Comment (bcwaldon) [inline conn.go]: Whoops, thanks for going above and beyond :)

**Comment by bcwaldon** [comment]
LGTM
