### PR TITLE
Set argument of SetProperty to Variant

### LINKED ISSUE #202: How to Set a Property Value?
I know I'm just doing something wrong, but can't figure out what it is. In this code I'm getting and setting the property value of an object. Getting the value works fine, but setting the value returns the following error:

```
No such method 'Set' in interface 'org.freedesktop.DBus.Properties' at object path '/KStars/Ekos/Capture' (signature 'sss')
```

Code in question:

```
package main

import (
	"github.com/godbus/dbus/v5"
)

func main() {
	conn, _ := dbus.SessionBus()
	obj := conn.Object("org.kde.kstars", "/KStars/Ekos/Capture")

	v, err := obj.GetProperty("org.kde.kstars.Ekos.Capture.camera")
	if err != nil {
		panic(err.Error())
	}
	println(v.Value().(string))

	err = obj.SetProperty("org.kde.kstars.Ekos.Capture.camera", "CCD Simulator")
	if err != nil {
		panic(err.Error())
	}
}
```

Example python code that works just fine:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import time
import dbus

bus = dbus.SessionBus()
remote_object = bus.get_object("org.kde.kstars", "/KStars/Ekos/Capture")
props = dbus.Interface(remote_object, "org.freedesktop.DBus.Properties")
properties = props.GetAll("org.kde.kstars.Ekos.Capture")
props.Set("org.kde.kstars.Ekos.Capture", "camera", "CCD Simulator")
```

Here's a link to the results of introspecting the object with:

```
	node, _ := introspect.Call(obj)
	d, _ := xml.MarshalIndent(node, "", "  ")
	println(string(d))
```

https://gist.github.com/rickbassham/99ac97b9d4fbf0747d4de5d2ccc6bc50

This introspection shows a `Set` method on `org.freedesktop.DBus.Properties`.

So, can someone point out what I'm doing wrong here, please? I don't really have any experience working DBus at all. I'm managed to get signals, methods, and getting properties to work fine with this package, just not setting properties.

Thanks!

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This function strictly takes a Variant, and other types will fail with error:

    No such interface “org.freedesktop.DBus.Properties” on object at path ...

Closes #202

### CODE REVIEW

File: object.go [hunk 1]
```diff
@@ -151,7 +151,7 @@ func (o *Object) StoreProperty(p string, value interface{}) error {
 
 // SetProperty calls org.freedesktop.DBus.Properties.Set on the given
 // object. The property name must be given in interface.member notation.
-func (o *Object) SetProperty(p string, v interface{}) error {
```
Comment (jsouthworth) [inline object.go:154]: Can we fix this in a compatible way? For instance, can we do ParseVariant if we are passed something other than a variant before call?

Comment (WhyNotHugo) [reply object.go:154]: Sorry, I don't quite follow.

Currently, passing anything that's _not_ a variant fails; only a variant works.

Comment (jsouthworth) [reply object.go:154]: The issue is that changing the function signature will break the API which means some consumers will need to update their code, just trying to avoid those issues.

Comment (WhyNotHugo) [reply object.go:154]: Do you have an example call that works **and** would require changes? I just don't see it :sweat:

Comment (jsouthworth) [reply object.go:154]: See: https://github.com/coreos/go-systemd/pull/296 for a problem that occurred due to a previous change like this.

Comment (jsouthworth) [reply object.go:154]: This kind of issue occurs when someone is referencing the function as a value in their code, the types won't match.

Comment (WhyNotHugo) [reply object.go:154]: Sorry, I don't think we're understanding each other completely.

This function's current signature states that it receives a `v interface{}`. However, anything that is not an a `v Variant` will crash.

There are currently two types of applications using this function:

- Those passing a `Variant`. Those will continue to work.
- Those passing a non-`Variant`. Those do not work and crash right now. So while the API change would require them to make changes, it would require them to make changes to code that crashed in the first place.

So what I mean was, do you have any example code that _does_ work not, but would break with this change?

Comment (jsouthworth) [reply object.go:154]: You are correct, the behavior is currently broken. The compatibility issue is if someone is referring to the function as a value changing its signature will cause their code to no longer compile, as was the case in the issue linked above. Making the change as currently done in this PR would require a v6 release of the godbus package API. Since we generally try to avoid these kind of breaking changes, what I'm asking you to do is make passing an interface work correctly instead of changing the function API. In my original comment I suggested having the interface converted to a variant if it wasn't already one when passed. Is this not possible?

Comment (WhyNotHugo) [reply object.go:154]: Ah, now I get your point!

I think the scenario for possible breakage is a bit of an edge case, and might not exist, but your proposed fix has better results anyway, so I'll go ahead and try to implement that.

Comment (jsouthworth) [reply object.go:154]: Yes it is an edge case but it is still an API change which means that if we follow the general guidelines for go modules we need to increment the version number so we don't arbitrarily break user code. As we've seen before the type of change introduced here can break user code (whether or not this one actually would can't be said as we don't know how everyone is using the library). Backwards compatibility is a pain but unless one designs a better API for the library generally it is best keep individual functions API compatible. In other words we want to avoid a "github.com/godbus/dbus/v6" library until such a time as we are making a significant intentional change to the API.

**Comment by WhyNotHugo** [comment]
I'm not entirely convinced by the results here; it someone passes an `int` then we're trying to set a property of type `int`, but if someone passes a `Variant<int>`, we're also trying to set a property of type `int`, **and not** `Variant<int>`.

I'm not sure which is the best behaviour with the current signature.

**Comment by guelfey** [comment]
But that would still be compatible to existing code - if you have a property that already is an actual Variant, you need to pass e.g. a `Variant<Variant<Int>>` here. This just makes this function a bit nicer to use if your property is not a Variant, which I'm fine with.

**Comment by WhyNotHugo** [comment]
Yeah, the main upside is that it maintains compatibility with existing code, but it's really unexpected behaviour and not a great API.

Maybe it's best to merge this as-is and refine it before a major release (at which point a breaking change might be acceptable).
